#!/usr/bin/env bash
# Builds the unattended attackrangelocal ISO.
#
# Inputs:
#   - .env at the repo root, fully populated (no REPLACE_ME values)
#   - The official Proxmox VE 8.2+ ISO (auto-downloaded if missing)
#   - `proxmox-auto-install-assistant` installed on this host
#       Debian/Ubuntu: apt install proxmox-auto-install-assistant
#       (Or build from source: github.com/proxmox/pve-installer)
#
# Output:
#   - iso/build/attackrangelocal-<RANGE_ID>-<DATE>.iso
#   - SHA256 printed to stdout
#
# After build:
#   sudo dd if=<ISO> of=/dev/sdX bs=4M status=progress conv=fsync
#   ... then boot the target machine from the USB.
set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ISO_DIR="${REPO_ROOT}/iso"
BUILD_DIR="${ISO_DIR}/build"
CACHE_DIR="${ISO_DIR}/cache"
PAYLOAD_STAGE="${BUILD_DIR}/payload"
mkdir -p "$BUILD_DIR" "$CACHE_DIR" "$PAYLOAD_STAGE"

# ---------- 1. Validate environment ----------
ENV_FILE="${REPO_ROOT}/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing .env. Copy ludus/.env.example to .env at the repo root first." >&2
  exit 1
fi
set -a; source "$ENV_FILE"; set +a

required=(RANGE_ID TS_AUTHKEY TS_API_KEY AD_DOMAIN_FQDN AD_DOMAIN_ADMIN
          AD_PASSWORD LUDUS_ADMIN_PASSWORD OPERATOR_SSH_PUBKEY TS_TAG)
for v in "${required[@]}"; do
  val="${!v:-}"
  if [[ -z "$val" || "$val" == REPLACE_ME* ]]; then
    echo "Required env var $v is unset or still a placeholder" >&2
    exit 1
  fi
done

if ! command -v proxmox-auto-install-assistant >/dev/null 2>&1; then
  echo "proxmox-auto-install-assistant not found." >&2
  echo "Install on Debian/Ubuntu: sudo apt install proxmox-auto-install-assistant" >&2
  exit 1
fi
if ! command -v envsubst >/dev/null 2>&1; then
  echo "envsubst not found (apt install gettext-base)" >&2
  exit 1
fi

# ---------- 2. Render answer.toml + secrets.env into stage ----------
echo "==> Rendering answer.toml and secrets.env..."
envsubst < "${ISO_DIR}/answer.toml.j2" > "${BUILD_DIR}/answer.toml"

# secrets.env is just the operator-supplied .env, baked into the ISO.
# It is NOT pulled from the network at runtime. Destroy the ISO after use.
cp "$ENV_FILE" "${PAYLOAD_STAGE}/secrets.env"
chmod 600 "${PAYLOAD_STAGE}/secrets.env"

# ---------- 3. Resolve the git ref to pin the wrapper to ----------
# The wrapped first-boot script `git clone`s the repo and checks out this
# exact commit, so the deployed range matches the one that built the ISO.
echo "==> Resolving git ref for reproducible deploy..."
: "${REPO_URL:=$(git -C "${REPO_ROOT}" config --get remote.origin.url)}"
# Translate sandbox proxy URLs to the canonical GitHub URL if applicable.
case "$REPO_URL" in
  *93percentai/attackrangelocal*) REPO_URL="https://github.com/93percentai/attackrangelocal.git" ;;
  *dgxn4/attackrangelocal*)       REPO_URL="https://github.com/93percentai/attackrangelocal.git" ;;
esac
: "${REPO_REF:=$(git -C "${REPO_ROOT}" rev-parse HEAD)}"
echo "    repo: $REPO_URL"
echo "    ref:  $REPO_REF"

# ---------- 4. Download Proxmox ISO (cached) ----------
# Pin to a Proxmox VE 8.x release. The auto-installer answer.toml format is
# stable across 8.2–8.4; PVE 9.x reorganised the installer and we haven't
# validated against it yet.
: "${PROXMOX_ISO_URL:=https://enterprise.proxmox.com/iso/proxmox-ve_8.4-1.iso}"
PROXMOX_ISO_NAME="$(basename "$PROXMOX_ISO_URL")"
PROXMOX_ISO="${CACHE_DIR}/${PROXMOX_ISO_NAME}"
if [[ ! -f "$PROXMOX_ISO" ]]; then
  echo "==> Downloading $PROXMOX_ISO_URL ..."
  curl -fL --retry 4 -o "$PROXMOX_ISO" "$PROXMOX_ISO_URL"
fi

# ---------- 5. Validate the answer file ----------
echo "==> Validating answer.toml..."
proxmox-auto-install-assistant validate-answer "${BUILD_DIR}/answer.toml"

# ---------- 6. Build the first-boot wrapper ----------
# PAI's prepare-iso accepts ONE first-boot executable, max 1 MiB. We can't
# embed the whole repo there, so the wrapper:
#   1. Drops the secrets.env (~1 KB) into /var/lib/proxmox-firstboot/
#   2. Exports REPO_URL + REPO_REF for the inlined first-boot body
#   3. Runs the first-boot body which `git clone`s and proceeds
# Total wrapper size: ~10 KB, well under the 1 MiB cap.
echo "==> Building first-boot wrapper..."
WRAPPED_FB="${BUILD_DIR}/first-boot-wrapped.sh"
SECRETS_B64=$(base64 -w0 "${PAYLOAD_STAGE}/secrets.env")
{
  echo '#!/usr/bin/env bash'
  echo "# Generated by iso/build-iso.sh on $(date -u +%FT%TZ)"
  echo "# DO NOT EDIT — regenerate with: ./iso/build-iso.sh"
  echo 'set -euo pipefail'
  echo
  echo 'mkdir -p /var/lib/proxmox-firstboot'
  echo "echo '$SECRETS_B64' | base64 -d > /var/lib/proxmox-firstboot/secrets.env"
  echo 'chmod 600 /var/lib/proxmox-firstboot/secrets.env'
  echo
  echo "export REPO_URL='$REPO_URL'"
  echo "export REPO_REF='$REPO_REF'"
  echo
  echo '# --- inlined iso/first-boot.sh body ---'
  # Skip the template's shebang + initial `set -euo pipefail`.
  sed '1,/^set -euo pipefail$/d' "${ISO_DIR}/first-boot.sh"
} > "$WRAPPED_FB"
chmod +x "$WRAPPED_FB"
echo "    Wrapper: $WRAPPED_FB  ($(du -h "$WRAPPED_FB" | cut -f1))"

# Pre-flight check the size limit so we fail clearly instead of via PAI.
WRAPPER_BYTES=$(stat -c '%s' "$WRAPPED_FB")
if [[ $WRAPPER_BYTES -gt 1048576 ]]; then
  echo "ERROR: wrapper is ${WRAPPER_BYTES} bytes; PAI caps first-boot at 1 MiB" >&2
  echo "       (likely cause: secrets.env grew unexpectedly)" >&2
  exit 1
fi

# ---------- 7. Bake the ISO ----------
DATE_TAG="$(date +%Y%m%d)"
OUT_ISO="${BUILD_DIR}/attackrangelocal-${RANGE_ID}-${DATE_TAG}.iso"
echo "==> Preparing custom ISO -> $OUT_ISO ..."
proxmox-auto-install-assistant prepare-iso \
  "$PROXMOX_ISO" \
  --fetch-from iso \
  --answer-file "${BUILD_DIR}/answer.toml" \
  --on-first-boot "$WRAPPED_FB" \
  --output "$OUT_ISO"

# ---------- 7. Hash + flash instructions ----------
echo
echo "============================================================"
echo "Built: $OUT_ISO"
sha256sum "$OUT_ISO"
echo "============================================================"
echo
echo "Flash to USB (replace /dev/sdX with the actual USB device):"
echo "  sudo dd if=$OUT_ISO of=/dev/sdX bs=4M status=progress conv=fsync"
echo
echo "Then boot the target Proxmox box from that USB. The install is"
echo "fully unattended; you'll be able to ssh root@ludus-host.<tailnet>"
echo "within ~5 minutes via Tailscale, and the full range will be UP"
echo "in roughly 3 hours."
