#!/usr/bin/env bash
# Configures the Proxmox host to use WiFi as its only uplink, with NAT
# (MASQUERADE) from vmbr0 → wlan. Designed to run on a freshly installed
# Proxmox VE host, called from iso/first-boot.sh when WIFI_ENABLE=true.
#
# Why NAT and not a bridge:
#   802.11 STA mode only accepts frames whose source MAC matches the
#   station. A Linux bridge would forward frames using the VM's MAC and
#   the AP would silently drop them. The canonical Proxmox-recommended
#   workaround (https://pve.proxmox.com/wiki/WLAN) is to NAT instead.
#
# Required env vars (typically sourced from /var/lib/proxmox-firstboot/secrets.env):
#   WIFI_SSID       Network name (1-32 chars)
#   WIFI_PASSWORD   WPA2-PSK pre-shared key
#   WIFI_COUNTRY    2-letter ISO regulatory code (default US)
#   WIFI_INTERFACE  Override the auto-detected interface (optional)
#   WIFI_DISABLE_WIRED_AFTER_BOOT  true = stop the install-time wired NIC
#
# Idempotent: re-running fixes a partial setup but does not break a
# working one. Exit non-zero on the first hard error.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Load baked secrets when invoked manually (`source secrets.env` in the parent
# shell does NOT export vars to this subprocess unless you used `set -a`).
if [[ -z "${WIFI_SSID:-}" || -z "${WIFI_PASSWORD:-}" ]]; then
  for secrets in /var/lib/proxmox-firstboot/secrets.env \
                 "${SCRIPT_DIR}/../.env" \
                 /opt/attackrangelocal/.env; do
    if [[ -f "$secrets" ]]; then
      set -a
      # shellcheck disable=SC1090
      source "$secrets"
      set +a
      break
    fi
  done
fi

: "${WIFI_SSID:?WIFI_SSID must be set (check /var/lib/proxmox-firstboot/secrets.env)}"
: "${WIFI_PASSWORD:?WIFI_PASSWORD must be set (check /var/lib/proxmox-firstboot/secrets.env)}"
WIFI_COUNTRY="${WIFI_COUNTRY:-US}"
WIFI_INTERFACE="${WIFI_INTERFACE:-}"
WIFI_DISABLE_WIRED_AFTER_BOOT="${WIFI_DISABLE_WIRED_AFTER_BOOT:-true}"
NAT_SUBNET="${NAT_SUBNET:-10.10.10.0/24}"
NAT_GATEWAY="${NAT_GATEWAY:-10.10.10.1/24}"

log()  { echo "[$(date -u +%FT%TZ)] wifi: $*"; }
fail() { echo "ERROR: $*" >&2; exit 1; }

# shellcheck source=lib/ensure-debian-apt.sh
source "${SCRIPT_DIR}/lib/ensure-debian-apt.sh"

# ---------- 1. Install firmware + tools (over the WIRED uplink) ----------
log "installing wpa_supplicant + non-free firmware (apt over wired)..."
ensure_debian_bookworm_apt
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  wpasupplicant wireless-tools iw rfkill iptables-persistent \
  firmware-iwlwifi firmware-realtek firmware-misc-nonfree \
  firmware-atheros firmware-brcm80211 || \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  wpasupplicant wireless-tools iw rfkill iptables-persistent \
  pve-firmware || \
  fail "apt install failed — WiFi firmware not pulled. Wired uplink working?"

# ---------- 2. Unblock the radio + set regdomain ----------
log "unblocking rfkill + setting regdomain to ${WIFI_COUNTRY}..."
rfkill unblock all || true
# Persist country across reboots
echo "REGDOMAIN=${WIFI_COUNTRY}" > /etc/default/crda
iw reg set "${WIFI_COUNTRY}" 2>/dev/null || \
  log "WARN: iw reg set failed (kernel may apply at first ifup instead)"

# ---------- 3. Find the WiFi interface ----------
if [[ -z "$WIFI_INTERFACE" ]]; then
  WIFI_INTERFACE="$(iw dev 2>/dev/null | awk '$1=="Interface"{print $2; exit}')"
fi
[[ -z "$WIFI_INTERFACE" ]] && fail "no WiFi interface found. Check 'iw dev' and 'lspci | grep -i wireless'."
log "using WiFi interface: ${WIFI_INTERFACE}"

# ---------- 4. Write wpa_supplicant config (hashed PSK, not plaintext) ----------
WPA_CONF="/etc/wpa_supplicant/wpa_supplicant-${WIFI_INTERFACE}.conf"
log "writing ${WPA_CONF}..."
install -d -m 0700 /etc/wpa_supplicant
cat > "$WPA_CONF" <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=${WIFI_COUNTRY}

EOF
# wpa_passphrase generates a hashed PSK so the plaintext password isn't
# written to disk in /etc/. The original plaintext is still in
# /var/lib/proxmox-firstboot/secrets.env which is mode 600.
wpa_passphrase "${WIFI_SSID}" "${WIFI_PASSWORD}" >> "$WPA_CONF"
chmod 600 "$WPA_CONF"

# ---------- 5. Configure /etc/network/interfaces.d/wifi (ifupdown2) ----------
log "writing /etc/network/interfaces.d/wifi..."
cat > /etc/network/interfaces.d/wifi <<EOF
# Generated by scripts/setup-wifi-uplink.sh
allow-hotplug ${WIFI_INTERFACE}
iface ${WIFI_INTERFACE} inet dhcp
    wpa-conf ${WPA_CONF}
    # Make WiFi the default route once it gets a DHCP lease.
    metric 100
EOF

# ---------- 6. Reconfigure vmbr0 for NAT (the canonical Proxmox WLAN pattern) ----------
log "reconfiguring vmbr0 for NAT through ${WIFI_INTERFACE}..."
# Find the installer's vmbr0 stanza and replace it. The installer creates
# vmbr0 bridged to the wired NIC; we need bridge-ports none + iptables NAT.
python3 - "$WIFI_INTERFACE" "$NAT_SUBNET" "$NAT_GATEWAY" <<'PYEOF'
import re, sys, pathlib
iface, subnet, gateway = sys.argv[1:4]
p = pathlib.Path("/etc/network/interfaces")
text = p.read_text()

new_block = f"""# vmbr0 reconfigured for WiFi NAT by attackrangelocal first-boot.
# Lab VMs (incl. Ludus router uplink) sit on this bridge; iptables
# MASQUERADE rewrites their packets to look like they came from {iface}.
auto vmbr0
iface vmbr0 inet static
    address {gateway}
    bridge-ports none
    bridge-stp off
    bridge-fd 0
    post-up   echo 1 > /proc/sys/net/ipv4/ip_forward
    post-up   iptables -t nat -C POSTROUTING -s {subnet} -o {iface} -j MASQUERADE 2>/dev/null || iptables -t nat -A POSTROUTING -s {subnet} -o {iface} -j MASQUERADE
    post-up   iptables -C FORWARD -i vmbr0 -o {iface} -j ACCEPT 2>/dev/null || iptables -A FORWARD -i vmbr0 -o {iface} -j ACCEPT
    post-up   iptables -C FORWARD -i {iface} -o vmbr0 -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || iptables -A FORWARD -i {iface} -o vmbr0 -m state --state RELATED,ESTABLISHED -j ACCEPT
    post-down iptables -t nat -D POSTROUTING -s {subnet} -o {iface} -j MASQUERADE 2>/dev/null || true
    post-down iptables -D FORWARD -i vmbr0 -o {iface} -j ACCEPT 2>/dev/null || true
    post-down iptables -D FORWARD -i {iface} -o vmbr0 -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null || true
"""

# Replace any existing `iface vmbr0 ...` block (auto + iface lines + indented body).
pat = re.compile(
    r"(^|\n)(auto\s+vmbr0\s*\n)?iface\s+vmbr0\s+inet[^\n]*\n(?:[ \t]+[^\n]*\n)*",
    re.MULTILINE,
)
if pat.search(text):
    text = pat.sub("\n" + new_block, text, count=1)
else:
    text += "\n" + new_block
p.write_text(text)
print("rewrote /etc/network/interfaces")
PYEOF

# ---------- 7. Persist ip_forward ----------
echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-attackrangelocal-forward.conf
sysctl -p /etc/sysctl.d/99-attackrangelocal-forward.conf >/dev/null

# ---------- 8. Bring up the WiFi + new vmbr0 ----------
log "ifreload to apply WiFi + new vmbr0..."
if command -v ifreload >/dev/null 2>&1; then
  ifreload -a || log "WARN: ifreload reported errors (continuing)"
else
  ifdown vmbr0 2>/dev/null || true
  ifup "${WIFI_INTERFACE}"
  ifup vmbr0
fi

# ---------- 9. Wait for WiFi to actually carry traffic ----------
log "waiting up to 120s for WiFi to provide connectivity..."
ok=0
for i in $(seq 1 60); do
  if ping -c1 -W2 -I "${WIFI_INTERFACE}" 1.1.1.1 >/dev/null 2>&1; then
    ok=1; break
  fi
  sleep 2
done
[[ $ok -eq 0 ]] && fail "WiFi never reached 1.1.1.1. Run: journalctl -u wpa_supplicant; ip addr show ${WIFI_INTERFACE}; iw ${WIFI_INTERFACE} link"
log "WiFi up. IP: $(ip -4 addr show "${WIFI_INTERFACE}" | awk '/inet /{print $2; exit}')"

# ---------- 10. Optionally tear down the install-time wired interface ----------
if [[ "${WIFI_DISABLE_WIRED_AFTER_BOOT,,}" == "true" ]]; then
  log "looking for wired interfaces to disable..."
  # Find ethernet interfaces (link/ether, not wlan, not lo, not vmbr*).
  for nic in $(ls /sys/class/net 2>/dev/null); do
    case "$nic" in
      lo|vmbr*|"${WIFI_INTERFACE}") continue ;;
      en*|eth*|enp*|eno*|enx*)
        if [[ -e "/sys/class/net/$nic/wireless" ]]; then continue; fi
        log "disabling wired interface: $nic"
        ifdown "$nic" 2>/dev/null || true
        ip link set "$nic" down 2>/dev/null || true
        # Comment the iface block out of /etc/network/interfaces so it
        # doesn't come back on reboot.
        sed -i "/^auto $nic\b/,/^$/ s/^/# /" /etc/network/interfaces 2>/dev/null || true
        sed -i "/^iface $nic\b/,/^[a-zA-Z]/ { /^[a-zA-Z]/!s/^/# / }" /etc/network/interfaces 2>/dev/null || true
        ;;
    esac
  done
fi

# ---------- 11. Persist iptables rules across reboots ----------
log "persisting iptables rules via netfilter-persistent..."
mkdir -p /etc/iptables
iptables-save  > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6 2>/dev/null || true
systemctl enable netfilter-persistent >/dev/null 2>&1 || true

log "WiFi uplink configured."
log "  interface: ${WIFI_INTERFACE}"
log "  NAT:       ${NAT_SUBNET} -> ${WIFI_INTERFACE} (MASQUERADE)"
log "  vmbr0:     ${NAT_GATEWAY}"
log "Test: 'ip route' should show default via WiFi; 'iptables -t nat -L POSTROUTING -n' should list the MASQUERADE rule."
